## Generated by react-native-podfix
## Only edit the static_frameworks array if needed

require 'cocoapods'

def pod_fix(pre_install)
  # Add your static frameworks below, separated by line break or space
  static_frameworks = %w[
  ]
  puts "[react-native-podfix] Overriding the build_type to static_framework for the following pods: #{$static_frameworks.join(', ')}"
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      bt = pod.send(:build_type)
      if static_frameworks.include?(pod.name)
        puts "[react-native-podfix] #{pod.name}: Overriding the build_type to static_framework"
        def pod.build_type
          Pod::BuildType.static_framework
        end
      end
    end
  end
end